create type public.user_role as enum ('admin','head_coach','assistant_coach','viewer');
create type public.player_status as enum ('signed_up','invited','attended','awaiting_decision','under_consideration','offer_planned','alternative_offer','rejection_planned','offer_sent','rejection_sent','accepted','declined','waiting_list','withdrawn');
create table public.teams (id uuid primary key default gen_random_uuid(), name text unique not null, league text, training_day text, training_time text, venue text, squad_limit int);
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role user_role not null default 'viewer');
create table public.coach_teams (coach_id uuid references public.profiles(id) on delete cascade, team_id uuid references public.teams(id) on delete cascade, primary key(coach_id,team_id));
create table public.players (id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, email text not null, phone text, applied_team_id uuid references public.teams(id), primary_position text, secondary_position text, trial_date date, attended boolean default false, status player_status default 'signed_up', offered_team_id uuid references public.teams(id), offered_position text, rejection_reason text, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.assessments (id uuid primary key default gen_random_uuid(), player_id uuid references public.players(id) on delete cascade, coach_id uuid references public.profiles(id), serving int check(serving between 1 and 5), passing int check(passing between 1 and 5), setting int check(setting between 1 and 5), attacking int check(attacking between 1 and 5), blocking int check(blocking between 1 and 5), defence int check(defence between 1 and 5), communication int check(communication between 1 and 5), attitude int check(attitude between 1 and 5), notes text, created_at timestamptz default now());
create table public.email_log (id uuid primary key default gen_random_uuid(), player_id uuid references public.players(id) on delete cascade, generated_by uuid references public.profiles(id), template_type text not null, subject text not null, body text not null, sent_at timestamptz, created_at timestamptz default now());
alter table public.teams enable row level security; alter table public.profiles enable row level security; alter table public.coach_teams enable row level security; alter table public.players enable row level security; alter table public.assessments enable row level security; alter table public.email_log enable row level security;
