import { useEffect, useState } from 'react'
import { AlertTriangle, Banknote, CalendarClock, Check, DatabaseBackup, Download, FileJson, Lock, Mail, Plus, ShieldCheck, ToggleLeft, ToggleRight, Trash2, Upload, UserPlus, Users } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { teams } from '../data/constants'
import type { CoachProfile, EmailSettings, FinanceSettings, SeasonSettings } from '../types'
import { formatCurrency } from '../utils/finance'
import { parseSystemBackup, systemBackupSummary, type SystemBackup } from '../utils/backup'

type Props = {
  settings: EmailSettings
  save: (settings: EmailSettings) => void | Promise<void>
  coachProfiles: CoachProfile[]
  isAdmin: boolean
  currentUid: string
  saveCoachProfile: (profile: CoachProfile) => void | Promise<void>
  financeSettings: FinanceSettings
  saveFinanceSettings: (settings: FinanceSettings) => void | Promise<void>
  seasonSettings: SeasonSettings
  saveSeasonSettings: (settings: SeasonSettings) => void | Promise<void>
  exportSystemBackup: () => void | Promise<unknown>
  restoreSystemBackup: (backup: SystemBackup) => void | Promise<void>
}

export function SettingsPage({ settings, save, coachProfiles, isAdmin, currentUid, saveCoachProfile, financeSettings, saveFinanceSettings, seasonSettings, saveSeasonSettings, exportSystemBackup, restoreSystemBackup }: Props) {
  const [draft, setDraft] = useState(settings)
  const [saved, setSaved] = useState(false)
  const [feeDraft,setFeeDraft]=useState(financeSettings)
  const [feesSaved,setFeesSaved]=useState(false)
  const [modeBusy,setModeBusy]=useState(false)
  const [backupBusy,setBackupBusy]=useState<'export'|'restore'|''>('')
  const [backupCandidate,setBackupCandidate]=useState<SystemBackup|null>(null)
  const [backupFilename,setBackupFilename]=useState('')
  const [backupConfirmation,setBackupConfirmation]=useState('')
  const [backupError,setBackupError]=useState('')
  useEffect(() => setDraft(settings), [settings])
  useEffect(()=>setFeeDraft(financeSettings),[financeSettings])
  const updateTeam = (team: string, field: keyof EmailSettings['teamDetails'][string], value: string) => setDraft(current => ({ ...current, teamDetails: { ...current.teamDetails, [team]: { ...current.teamDetails[team], [field]: value } } }))
  const submit = async () => { await save(draft); setSaved(true); window.setTimeout(() => setSaved(false), 1800) }
  const submitFees=async()=>{await saveFinanceSettings(feeDraft);setFeesSaved(true);window.setTimeout(()=>setFeesSaved(false),1800)}
  const toggleTrialsMode=async()=>{if(!isAdmin||modeBusy)return;setModeBusy(true);try{await saveSeasonSettings({...seasonSettings,trialsMode:!seasonSettings.trialsMode})}finally{setModeBusy(false)}}
  const addDirectDebitDate=()=>setFeeDraft(current=>({...current,directDebitDueDates:[...current.directDebitDueDates,'']}))
  const setDirectDebitDate=(index:number,value:string)=>setFeeDraft(current=>({...current,directDebitDueDates:current.directDebitDueDates.map((date,itemIndex)=>itemIndex===index?value:date)}))
  const removeDirectDebitDate=(index:number)=>setFeeDraft(current=>({...current,directDebitDueDates:current.directDebitDueDates.filter((_,itemIndex)=>itemIndex!==index)}))
  const exportBackup=async()=>{setBackupBusy('export');setBackupError('');try{await exportSystemBackup()}catch(error){setBackupError(error instanceof Error?error.message:'The system backup could not be exported.')}finally{setBackupBusy('')}}
  const chooseBackup=async(file:File|undefined)=>{setBackupCandidate(null);setBackupFilename('');setBackupConfirmation('');setBackupError('');if(!file)return;try{const backup=parseSystemBackup(await file.text());setBackupCandidate(backup);setBackupFilename(file.name)}catch(error){setBackupError(error instanceof Error?error.message:'The selected backup could not be read.')}}
  const restoreBackup=async()=>{if(!backupCandidate||backupConfirmation!=='RESTORE')return;if(!window.confirm('Restore this backup now? A current pre-restore backup will download first, then all backed-up application data will replace the live data.'))return;setBackupBusy('restore');setBackupError('');try{await restoreSystemBackup(backupCandidate)}catch(error){setBackupError(error instanceof Error?error.message:'The system backup could not be restored.');setBackupBusy('')}}
  const backupSummary=backupCandidate?systemBackupSummary(backupCandidate):null

  return <><PageHeader title="Settings" subtitle="Shared communication, team and calendar details used by every coach." action={<button className="primary" onClick={submit}>{saved ? <Check/> : null}{saved ? 'Saved' : 'Save club settings'}</button>}/>
    {isAdmin&&<section className={`panel trials-mode-panel ${seasonSettings.trialsMode?'enabled':'disabled'}`}><div className="trials-mode-icon">{seasonSettings.trialsMode?<ToggleRight/>:<ToggleLeft/>}</div><div><span className="eyebrow">ADMINISTRATOR MODE CONTROL</span><h2>Trials Mode is {seasonSettings.trialsMode?'on':'off'}</h2><p>{seasonSettings.trialsMode?'All trial assessment, decision, email and squad-planning features are available.':'The portal is simplified for normal club operations: emails and trial planning are hidden, while schedules, confirmed squads, attendance and finance remain available.'}</p></div><button className={seasonSettings.trialsMode?'danger-outline':'primary'} disabled={modeBusy} onClick={toggleTrialsMode}>{modeBusy?'Updating…':seasonSettings.trialsMode?'Turn Trials Mode off':'Turn Trials Mode on'}</button></section>}
    {isAdmin&&<section className="panel system-backup-panel"><div className="panel-head"><div><span className="eyebrow">SYSTEM BACKUP</span><h2>Export or restore all application data</h2><p>Includes players, assessments, decisions, emails, schedules, attendance, teams, finance, settings, archives, account permissions, photos, stars and activity history.</p></div><DatabaseBackup/></div><div className="system-backup-grid"><article><Download/><div><h3>Download a backup</h3><p>Save a timestamped JSON snapshot somewhere secure. Firebase Authentication login credentials are not included.</p><button className="primary" disabled={Boolean(backupBusy)} onClick={exportBackup}>{backupBusy==='export'?'Preparing backup…':<><Download/>Export system data</>}</button></div></article><article className="restore-backup-card"><Upload/><div><h3>Restore from a backup</h3><p>Selecting a file only validates and previews it. Nothing changes until you confirm the restore.</p><label className="backup-file-picker"><FileJson/>{backupFilename||'Choose backup JSON'}<input type="file" accept="application/json,.json" disabled={Boolean(backupBusy)} onChange={event=>{const file=event.target.files?.[0];event.target.value='';void chooseBackup(file)}}/></label>{backupCandidate&&backupSummary&&<div className="backup-preview"><b>{new Date(backupCandidate.exportedAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</b><span>{backupSummary.players} players · {backupSummary.events} events · {backupSummary.archives} season archives · {backupSummary.photos} photos</span></div>}{backupCandidate&&<div className="backup-restore-confirm"><AlertTriangle/><p>This replaces current application data. A pre-restore backup downloads automatically first.</p><label>Type <strong>RESTORE</strong> to continue<input value={backupConfirmation} onChange={event=>setBackupConfirmation(event.target.value.toUpperCase())} placeholder="RESTORE" autoComplete="off"/></label><button className="danger" disabled={backupConfirmation!=='RESTORE'||Boolean(backupBusy)} onClick={restoreBackup}>{backupBusy==='restore'?'Restoring…':'Restore system data'}</button></div>}</div></article></div>{backupError&&<p className="system-backup-error"><AlertTriangle/>{backupError}</p>}</section>}
    <section className="settings-grid email-settings-grid">
      <div className="panel settings-card"><span className="eyebrow">EMAIL DEFAULTS</span><h2>Club communication</h2><p>Individual coach accounts now sign emails with their saved display name automatically.</p><label>Club name<input value={draft.clubName} onChange={event => setDraft({ ...draft, clubName: event.target.value })}/></label><label>Club contact email<input type="email" value={draft.clubEmail} onChange={event => setDraft({ ...draft, clubEmail: event.target.value })} placeholder="Added to CC on generated emails"/></label><label>Shared-login coach name<input value={draft.defaultCoachName} onChange={event => setDraft({ ...draft, defaultCoachName: event.target.value })} placeholder="Used only by the shared PIN account"/></label><div className="settings-note"><Mail/><span>The club contact and relevant team administrator contacts are added to CC when a coach opens a generated email draft.</span></div></div>
      <div className="panel settings-card"><span className="eyebrow">ACCESS</span><h2>Club accounts</h2><p>Coaches and team administrators can work with player profiles. Team Planner changes remain limited to their assigned teams.</p><ol className="coach-account-steps"><li><span>1</span>Create the person in Firebase Authentication.</li><li><span>2</span>Ask them to sign in once.</li><li><span>3</span>Return here, choose their role and assign their team.</li></ol><div className="settings-note secure"><ShieldCheck/><span>The shared PIN account remains a full administrator with access to every team and Finance.</span></div><div className="settings-note"><UserPlus/><span>Disable or delete the Firebase user when they leave the role.</span></div></div>
    </section>
    {isAdmin&&<section className="panel standard-fees-panel"><div className="panel-head"><div><span className="eyebrow">ADMINISTRATOR ONLY</span><h2>Season fees and payment schedule</h2><p>Set standard fees and the dates used to flag overdue player payments.</p></div><Banknote/></div><div className="standard-fee-grid"><label><span>NVL standard fee</span><small>Aces and Ravens</small><div className="settings-money-input"><span>£</span><input type="number" min="0" step="0.01" value={feeDraft.nvlFee||''} onChange={event=>setFeeDraft({...feeDraft,nvlFee:Number(event.target.value)})}/></div><em>{formatCurrency(feeDraft.nvlFee)} per player</em></label><label><span>LVA standard fee</span><small>Cobras, Coyotes, Llamas, Meerkats, Leopards and Pirates</small><div className="settings-money-input"><span>£</span><input type="number" min="0" step="0.01" value={feeDraft.lvaFee||''} onChange={event=>setFeeDraft({...feeDraft,lvaFee:Number(event.target.value)})}/></div><em>{formatCurrency(feeDraft.lvaFee)} per player</em></label><div className="standard-fee-action"><ShieldCheck/><p>These values and all player payment records are protected by administrator-only Firebase rules.</p><button className="primary" onClick={submitFees}>{feesSaved?<Check/>:null}{feesSaved?'Schedule saved':'Save fees and dates'}</button></div></div><div className="payment-schedule-settings"><header><CalendarClock/><div><h3>Payment deadlines</h3><p>Players are checked against the schedule matching their selected payment arrangement.</p></div></header><div className="payment-deadline-grid"><label><span>Fully paid deadline</span><input type="date" value={feeDraft.fullPaymentDueDate} onChange={event=>setFeeDraft({...feeDraft,fullPaymentDueDate:event.target.value})}/></label><label><span>First instalment</span><input type="date" value={feeDraft.instalmentOneDueDate} onChange={event=>setFeeDraft({...feeDraft,instalmentOneDueDate:event.target.value})}/></label><label><span>Second instalment</span><input type="date" min={feeDraft.instalmentOneDueDate} value={feeDraft.instalmentTwoDueDate} onChange={event=>setFeeDraft({...feeDraft,instalmentTwoDueDate:event.target.value})}/></label></div><div className="direct-debit-dates"><div><span><b>Direct debit collection dates</b><small>Add every planned collection date. The expected balance is divided equally across these dates.</small></span><button className="secondary" onClick={addDirectDebitDate}><Plus/>Add date</button></div>{feeDraft.directDebitDueDates.map((date,index)=><label key={`${index}-${date}`}><span>Collection {index+1}</span><input type="date" value={date} onChange={event=>setDirectDebitDate(index,event.target.value)}/><button aria-label={`Remove direct debit collection ${index+1}`} onClick={()=>removeDirectDebitDate(index)}><Trash2/></button></label>)}{!feeDraft.directDebitDueDates.length&&<p>No direct debit dates set. Add the first collection date when the schedule is agreed.</p>}</div></div></section>}
    <section className="panel coach-access-panel"><div className="panel-head"><div><span className="eyebrow">TEAM PERMISSIONS</span><h2>Who can edit each squad?</h2><p>Unassigned teams remain visible but become read-only in the Team Planner.</p></div>{isAdmin?<ShieldCheck/>:<Lock/>}</div>{!isAdmin?<div className="access-readonly"><Lock/><div><b>Administrator access required</b><span>Use the shared PIN account to change coach team assignments.</span></div></div>:coachProfiles.length?<div className="coach-access-list">{coachProfiles.map(profile=><CoachAccessRow key={profile.uid} profile={profile} currentUid={currentUid} save={saveCoachProfile}/>)}</div>:<div className="access-empty"><Users/><b>No coach profiles yet</b><span>Coaches appear here after their first successful sign-in.</span></div>}</section>
    <section className="panel team-email-settings"><div className="panel-head"><div><span className="eyebrow">TEAM DETAILS</span><h2>Contacts, training, competition and calendar colours</h2><p>Team administrator contacts are added to CC for the team options used by each generated email.</p></div><Mail/></div><div className="team-email-table-wrap"><table className="team-email-table"><thead><tr><th>Team</th><th>Team admin email</th><th>Calendar colour</th><th>Training day</th><th>Time</th><th>Venue</th><th>Competition / division</th></tr></thead><tbody>{teams.map(team => <tr key={team}><td><b>{team}</b></td><td><input type="email" value={draft.teamDetails[team].adminEmail} onChange={event => updateTeam(team,'adminEmail',event.target.value)} placeholder="Added to CC"/></td><td><label className="team-colour-control"><input type="color" value={draft.teamDetails[team].calendarColor} onChange={event=>updateTeam(team,'calendarColor',event.target.value)}/><span>{draft.teamDetails[team].calendarColor}</span></label></td><td><input value={draft.teamDetails[team].trainingDay} onChange={event => updateTeam(team,'trainingDay',event.target.value)} placeholder="e.g. Wednesday"/></td><td><input type="time" value={draft.teamDetails[team].trainingTime} onChange={event => updateTeam(team,'trainingTime',event.target.value)}/></td><td><input value={draft.teamDetails[team].venue} onChange={event => updateTeam(team,'venue',event.target.value)} placeholder="Training venue"/></td><td><input value={draft.teamDetails[team].competition} onChange={event => updateTeam(team,'competition',event.target.value)} placeholder="League and division"/></td></tr>)}</tbody></table></div></section>
  </>
}

function CoachAccessRow({profile,currentUid,save}:{profile:CoachProfile;currentUid:string;save:(profile:CoachProfile)=>void|Promise<void>}){
  const admin=profile.role==='admin'
  const teamAdmin=profile.role==='team-admin'
  const [nameDraft,setNameDraft]=useState(profile.displayName)
  useEffect(()=>setNameDraft(profile.displayName),[profile.displayName])
  const toggleTeam=(team:string)=>teamAdmin?save({...profile,teams:{[team]:true}}):save({...profile,teams:{...profile.teams,[team]:!profile.teams[team]}})
  const changeRole=(role:CoachProfile['role'])=>{const firstAssigned=teams.find(team=>profile.teams[team]);save({...profile,role,teams:role==='team-admin'?(firstAssigned?{[firstAssigned]:true}:{}):profile.teams})}
  const saveName=()=>{const displayName=nameDraft.trim();if(displayName&&displayName!==profile.displayName)save({...profile,displayName});else setNameDraft(profile.displayName)}
  return <div className="coach-access-row"><div className="coach-access-identity"><div>{(nameDraft||profile.email).slice(0,2).toUpperCase()}</div><span><label className="coach-name-field">Coach name{profile.uid===currentUid?' (you)':''}<input value={nameDraft} onChange={event=>setNameDraft(event.target.value)} onBlur={saveName} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur()}}/></label><small>{profile.email}</small></span></div><label className="role-select">Access level<select value={profile.role} disabled={profile.uid===currentUid} onChange={event=>changeRole(event.target.value as CoachProfile['role'])}><option value="coach">Coach</option><option value="assistant-coach">Assistant coach</option><option value="team-admin">Team administrator</option><option value="admin">Administrator</option></select></label><div className="coach-team-access"><span>{admin?'All teams':teamAdmin?'Own team':'Assigned teams'}</span><div>{teams.map(team=><button key={team} disabled={admin} className={admin||profile.teams[team]?'selected':''} onClick={()=>toggleTeam(team)}>{(admin||profile.teams[team])&&<Check/>}{team}</button>)}</div>{teamAdmin&&<small className="team-admin-help">Selecting a team replaces the previous team assignment.</small>}</div></div>
}
