import { useMemo, useState, type ReactNode } from 'react'
import { AlertTriangle, CalendarDays, Check, CheckCircle2, Clock3, Mail, MapPin, Phone, Search, ShieldCheck, Trash2, UserPlus, Volleyball, X } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { clubSignupOutcomeLabel, clubSignupOutcomeOptions, clubSignupStatusLabel, clubSignupStatuses, type ClubSignup, type ClubSignupOutcome, type ClubSignupStatus } from '../signup/types'
import '../signup/Signup.css'

type Props={signups:ClubSignup[];ready:boolean;loadError:string;readOnly:boolean;updateStatus:(id:string,status:ClubSignupStatus,outcome:ClubSignupOutcome|'')=>Promise<void>;deleteSignup:(id:string)=>Promise<void>}
type PendingStatus={signupId:string;playerName:string;status:Exclude<ClubSignupStatus,'new'>;outcome:ClubSignupOutcome|''}
const date=(value:number)=>value?new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'—'

export function SignupInboxPage({signups,ready,loadError,readOnly,updateStatus,deleteSignup}:Props){
  const [status,setStatus]=useState<ClubSignupStatus|'all'>('new')
  const [query,setQuery]=useState('')
  const [selectedId,setSelectedId]=useState('')
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const [pendingStatus,setPendingStatus]=useState<PendingStatus|null>(null)
  const [pendingDelete,setPendingDelete]=useState<{signupId:string;playerName:string}|null>(null)
  const visible=useMemo(()=>signups.filter(item=>(status==='all'||item.status===status)&&`${item.name} ${item.email} ${item.primaryPosition} ${item.interestedDivisions.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())),[signups,status,query])
  const selected=signups.find(item=>item.id===selectedId)||visible[0]||null
  const counts=Object.fromEntries(clubSignupStatuses.map(value=>[value,signups.filter(item=>item.status===value).length])) as Record<ClubSignupStatus,number>
  const saveStatus=async(id:string,next:ClubSignupStatus,outcome:ClubSignupOutcome|'')=>{setBusy(true);setError('');try{await updateStatus(id,next,outcome);return true}catch{setError('The sign-up status could not be updated. Please try again.');return false}finally{setBusy(false)}}
  const requestStatus=async(next:ClubSignupStatus)=>{if(!selected||readOnly||next===selected.status)return;if(next==='new'){await saveStatus(selected.id,next,'');return}setError('');setPendingStatus({signupId:selected.id,playerName:selected.name,status:next,outcome:''})}
  const confirmStatus=async()=>{if(!pendingStatus||!pendingStatus.outcome)return;if(await saveStatus(pendingStatus.signupId,pendingStatus.status,pendingStatus.outcome))setPendingStatus(null)}
  const closeStatus=()=>{if(!busy){setPendingStatus(null);setError('')}}
  const requestDelete=()=>{if(!selected||readOnly)return;setError('');setPendingDelete({signupId:selected.id,playerName:selected.name})}
  const closeDelete=()=>{if(!busy){setPendingDelete(null);setError('')}}
  const confirmDelete=async()=>{if(!pendingDelete)return;setBusy(true);setError('');try{await deleteSignup(pendingDelete.signupId);setSelectedId('');setPendingDelete(null)}catch{setError('The sign-up could not be deleted. Please try again.')}finally{setBusy(false)}}
  return <>
    <PageHeader title="Club sign-ups" subtitle="Expressions of interest submitted through the public club form." action={<a className="secondary signup-public-link" href="/signup" target="_blank" rel="noreferrer"><UserPlus/>Open public form</a>}/>
    <section className="signup-manager-stats"><button className={status==='new'?'active':''} onClick={()=>setStatus('new')}><UserPlus/><span>New</span><b>{counts.new}</b></button><button className={status==='contacted'?'active':''} onClick={()=>setStatus('contacted')}><Phone/><span>Contacted</span><b>{counts.contacted}</b></button><button className={status==='closed'?'active':''} onClick={()=>setStatus('closed')}><CheckCircle2/><span>Closed</span><b>{counts.closed}</b></button></section>
    {readOnly&&<div className="signup-readonly"><ShieldCheck/>You can view sign-ups, but this Welfare account cannot change their status.</div>}
    {loadError&&<div className="signup-error signup-load-error">{loadError}</div>}
    <section className="signup-manager-layout panel">
      <aside className="signup-manager-list"><div className="signup-manager-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search sign-ups"/></label><select aria-label="Filter sign-ups" value={status} onChange={event=>setStatus(event.target.value as ClubSignupStatus|'all')}><option value="all">All statuses</option>{clubSignupStatuses.map(value=><option value={value} key={value}>{clubSignupStatusLabel(value)}</option>)}</select></div>{!ready?<div className="signup-manager-empty">Loading sign-ups…</div>:visible.length?visible.map(item=><button key={item.id} className={selected?.id===item.id?'active':''} onClick={()=>setSelectedId(item.id)}>{item.profilePhoto?<img className="signup-list-photo" src={item.profilePhoto} alt=""/>:<span className="signup-list-initials">{item.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</span>}<span><b>{item.name}</b><small>{item.primaryPosition} · {item.interestedDivisions.join(', ')}</small></span><i className={item.status}>{clubSignupStatusLabel(item.status)}</i><time>{date(item.createdAt)}</time></button>):<div className="signup-manager-empty"><UserPlus/><b>No matching sign-ups</b><span>New expressions of interest will appear here.</span></div>}</aside>
      <div className="signup-manager-detail">{selected?<><header><div className="signup-detail-identity">{selected.profilePhoto?<img src={selected.profilePhoto} alt={`${selected.name} profile`}/>:<span>{selected.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</span>}<div><span className={`signup-status ${selected.status}`}>{clubSignupStatusLabel(selected.status)}</span><h2>{selected.name}</h2><p>Submitted {date(selected.createdAt)} · {selected.id}</p></div></div>{!readOnly&&<div className="signup-manager-actions"><select value={selected.status} disabled={busy} onChange={event=>void requestStatus(event.target.value as ClubSignupStatus)}>{clubSignupStatuses.map(value=><option value={value} key={value}>{clubSignupStatusLabel(value)}</option>)}</select><button type="button" className="signup-delete-button" disabled={busy} onClick={requestDelete}><Trash2/>Delete</button></div>}</header>{error&&!pendingStatus&&!pendingDelete&&<div className="signup-error">{error}</div>}
        <div className="signup-contact-actions"><a href={`mailto:${selected.email}`}><Mail/>{selected.email}</a><a href={`tel:${selected.phone}`}><Phone/>{selected.phone}</a></div>
        <section className="signup-detail-section"><h3>Player details</h3><div className="signup-detail-grid"><Detail icon={<CalendarDays/>} label="Date of birth" value={new Date(`${selected.dateOfBirth}T12:00:00`).toLocaleDateString('en-GB',{dateStyle:'long'})}/><Detail icon={<Volleyball/>} label="Playing category" value={selected.playingCategory}/><Detail icon={<Volleyball/>} label="Interested divisions" value={selected.interestedDivisions.join(', ')}/><Detail icon={<Volleyball/>} label="Positions" value={`${selected.primaryPosition}${selected.secondaryPosition?` / ${selected.secondaryPosition}`:''}`}/><Detail icon={<ShieldCheck/>} label="Highest level" value={selected.highestLevelPlayed}/><Detail icon={<MapPin/>} label="Current / recent club" value={selected.currentClub||'Not provided'}/></div></section>
        <TextBlock title="Playing experience" value={selected.playingExperience}/>
        <TextBlock title="Availability" value={selected.availability}/>
        {selected.notes&&<TextBlock title="Additional information" value={selected.notes}/>}
        {selected.heardAboutUs&&<TextBlock title="How they heard about us" value={selected.heardAboutUs}/>}
        {selected.statusOutcome&&<TextBlock title="Latest status outcome" value={clubSignupOutcomeLabel(selected.statusOutcome)}/>}
        {selected.handledBy&&<div className="signup-handled"><Clock3/>Last updated by {selected.handledBy} on {date(selected.updatedAt)}</div>}
      </>:<div className="signup-manager-empty detail"><UserPlus/><h2>Select a sign-up</h2><p>Contact details and playing information will appear here.</p></div>}</div>
    </section>
    {pendingStatus&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&closeStatus()}><section className="signup-status-modal" role="dialog" aria-modal="true" aria-labelledby="signup-status-title"><header><div><span className="eyebrow">{clubSignupStatusLabel(pendingStatus.status)} sign-up</span><h2 id="signup-status-title">What happened with {pendingStatus.playerName}?</h2><p>Select an outcome before changing this sign-up to {clubSignupStatusLabel(pendingStatus.status).toLowerCase()}.</p></div><button type="button" onClick={closeStatus} disabled={busy} aria-label="Close"><X/></button></header><div className="signup-status-options">{clubSignupOutcomeOptions[pendingStatus.status].map((option,index)=><button type="button" autoFocus={index===0} className={pendingStatus.outcome===option.value?'selected':''} key={option.value} onClick={()=>setPendingStatus(current=>current?{...current,outcome:option.value}:current)}><span>{pendingStatus.outcome===option.value?<Check/>:index+1}</span><b>{option.label}</b></button>)}</div>{error&&<div className="signup-error">{error}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={closeStatus}>Cancel</button><button type="button" className="primary" disabled={busy||!pendingStatus.outcome} onClick={()=>void confirmStatus()}>{busy?'Saving…':`Save as ${clubSignupStatusLabel(pendingStatus.status)}`}</button></footer></section></div>}
    {pendingDelete&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&closeDelete()}><section className="signup-status-modal signup-delete-modal" role="alertdialog" aria-modal="true" aria-labelledby="signup-delete-title"><header><div><span className="eyebrow">Delete sign-up</span><h2 id="signup-delete-title">Delete {pendingDelete.playerName}?</h2><p>This permanently removes their sign-up and all submitted details.</p></div><button type="button" onClick={closeDelete} disabled={busy} aria-label="Close"><X/></button></header><div className="signup-delete-warning"><AlertTriangle/><div><b>This cannot be undone</b><p>The player’s contact details, profile photo, playing information and recorded outcome will be deleted.</p></div></div>{error&&<div className="signup-error">{error}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={closeDelete}>Cancel</button><button type="button" className="signup-delete-confirm" disabled={busy} onClick={()=>void confirmDelete()}><Trash2/>{busy?'Deleting…':'Delete sign-up'}</button></footer></section></div>}
  </>
}

function Detail({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div>{icon}<span><small>{label}</small><b>{value||'Not provided'}</b></span></div>}
function TextBlock({title,value}:{title:string;value:string}){return <section className="signup-detail-section"><h3>{title}</h3><p>{value}</p></section>}
